#!/bin/bash

ey recipes upload -e CircleBuilder
ey recipes apply -e CircleBuilder
ey recipes upload -e JewishBuilder
ey recipes apply -e JewishBuilder
ey recipes upload -e Cirple
ey recipes apply -e Cirple
ey recipes upload -e IsMySocialNetwork
ey recipes apply -e IsMySocialNetwork
ey recipes upload -e MarriageNetwork
ey recipes apply -e MarriageNetwork

ey recipes upload -e CatholicLoyalty
ey recipes apply -e CatholicLoyalty
ey recipes upload -e HelpWW
ey recipes apply -e HelpWW
